### ISSUE TITLE
没有发现 exhide 扩展 ，模糊查找时，不能隐藏相关节点，filter功能

### ISSUE THREAD

**Issue by huanghd5631** [tower1229/Vue-Giant-Tree#16]

**Comment by tower1229** [comment]
官方文档：
> all.js = core + excheck + exedit ( 不包括 exhide ); 

默认就是不包含exhide扩展的，通常搜索过滤都是后端接口做，如果是前端过滤的场景，可能需要自己整合exhide扩展了，sorry
