### ISSUE TITLE
git 源码本地 安装组件出现错误

### ISSUE THREAD

**Issue by zero324** [tower1229/Vue-Giant-Tree#17]
Not Found - GET https://registry.npmjs.org/es-abstract/-/es-abstract-1.14.0.tgz

项目集成vue-giant-tree组件   使用时  出现 init of undefined 问题  项目的jquery版本 3.1.1    jquery升级到3.5.1  还是出现同样问题

**Comment by tower1229** [comment]
Vue-Giant-Tree自身也依赖了jQuery，并且会尝试把jQuery挂载到window上，
```js
import * as $ from "jquery";
if (!window.jQuery) {
  window.jQuery = $;
}
...
```
如果这个报错发生在Vue-Giant-Tree组件内的话，怀疑是jQuery冲突了，可以尝试去掉项目本身的jQuery依赖试下
