### ISSUE TITLE
异步加载数据时setting无法根据传进来的值自动刷新，只能默认第一次传给giant-tree的值

### ISSUE THREAD

**Issue by asdip138** [tower1229/Vue-Giant-Tree#18]
treeSetting: {
        async: {
          enable: true,
          url: `XXXXX`,
          autoParam: ['code'],
          contentType: 'application/json',
          headers: {
            //其他自定义header参数
            'custom_request_id': guidUtils.build()
          },
        },
        callback: {
          beforeAsync: function(treeId, treeNode) {
            vm.treeSetting.async.headers['custom_request_id'] = guidUtils.build()
            console.log('beforeAsync', treeId, treeNode)
          },
          onAsyncSuccess: function(event, treeId, treeNode, msg) {
            console.log('onAsyncSuccess', event, treeId, treeNode, msg)
          }
     },
 }

如代码，我的setting.async.headers有个自定义参数custom_request_id是一个随机数，每次请求时应该变化，我在callback.beforeAsync钩子做了处理去更新该参数的值，观察giant-tree组件的props里的setting.async.headers.custom_request_id的值，每次请求时确实已经更新，但是查看network request，每次调用api传的值都是第一次生成的值。

**Comment by tower1229** [comment]
这个是zTree自身就没有兼容这种情况，其内部实现应该是，初始化检测到async参数就直接用当下的参数生成了ajax实例，后续的参数变化就不会再应用到ajax请求中了，你这个情况最好协调后端不要在header里接收随机数
