### ISSUE TITLE
树形组件有没考虑支持搜索功能呢？

### ISSUE THREAD

**Issue by fengyun2** [tower1229/Vue-Giant-Tree#2]
期望的效果如下：

![image](https://user-images.githubusercontent.com/8147202/64397457-eeff7600-d093-11e9-9c50-a57df80a30d4.png)

**Comment by tower1229** [comment]
没有，而且这完全是两种不同的场景，Vue-Giant-Tree只针对大量数据渲染的场景，搜索下拉这种完全可以通过服务端请求来避免前端展现大数据量，类似的成熟组件有很多

**Comment by fengyun2** [comment]
@tower1229 这个只是纯前端的搜索
