### ISSUE TITLE
是否不支持confirmRename事件呢

### ISSUE THREAD

**Issue by zhanjinfeng** [tower1229/Vue-Giant-Tree#21]
用来校验编辑后的节点名称

**Comment by tower1229** [comment]
ztree的事件都支持，但是ztree文档我也没找到这个confirmRename事件

**Comment by zhanjinfeng** [comment]
有的 v2.6版本新增的事件

**Comment by tower1229** [comment]
http://www.treejs.cn/v3/api.php  最新版没有这个事件，但是有个类似的beforeRename
