### ISSUE TITLE
能不能提供js文件

### ISSUE THREAD

**Issue by hbh112233abc** [tower1229/Vue-Giant-Tree#23]
能不能提供js文件 方便单页html直接引用呢?

**Comment by tower1229** [comment]
umd版本就是直接引用的，见demo：https://github.com/tower1229/Vue-Giant-Tree/blob/master/dist/demo.html

**Comment by hunteryun** [comment]
怎么肥四？跑不起来啊，要么是Uncaught ReferenceError: vue is not defined，加了单引号后，又提示Invalid Component definition: vue-giant-tree， 你测过吗？

**Comment by tower1229** [comment]
> 怎么肥四？跑不起来啊，要么是Uncaught ReferenceError: vue is not defined，加了单引号后，又提示Invalid Component definition: vue-giant-tree， 你测过吗？

好吧，那个demo.html是vue-cli自动构建出来的，没有测试数据组件注册的也有问题，本来就跑不起来，我手动改了一下，现在可以运行了
