### ISSUE TITLE
在PUBLIC下的index.html中引入其他JS(依赖了jquery)的时候,使用Vue-Giant-Tree出现报错

### ISSUE THREAD

**Issue by shuangyue521** [tower1229/Vue-Giant-Tree#28]
Firefox出现 jquery.fn.zTree is undefined
Chrome出现 Cannot read property 'init' of undefined

![index](https://user-images.githubusercontent.com/32632410/118902295-f4742100-b947-11eb-8b80-f3bdc0f5c117.png)
![封装组件1](https://user-images.githubusercontent.com/32632410/118902300-f6d67b00-b947-11eb-9f2c-7943ad41ddba.png)
![封装组件2](https://user-images.githubusercontent.com/32632410/118902301-f76f1180-b947-11eb-8cec-447227f67969.png)

**Comment by tower1229** [comment]
嗯，解决了，https://github.com/tower1229/Vue-Giant-Tree/commit/32565420f04f72fd7d2d042d53c575a92fcf2726

**Comment by shuangyue521** [comment]
仍未解决，不好意思

**Comment by shuangyue521** [comment]
> 嗯，解决了，[3256542](https://github.com/tower1229/Vue-Giant-Tree/commit/32565420f04f72fd7d2d042d53c575a92fcf2726)

仍未解决，不好意思

**Comment by Lq-q** [comment]
我也遇到这个问题了，在public下的index.html中引入了jquery，其他插件需要，<script type="text/javascript" src="./static/jquery-3.6.0.min.js"></script>，也出现了题主的报错信息

**Comment by Lq-q** [comment]
"vue-giant-tree": "^0.1.5", 引入的事0.1.5的版本
