### ISSUE TITLE
出现 init of undefined错误

### ISSUE THREAD

**Issue by HuaChuDev** [tower1229/Vue-Giant-Tree#30]
使用vue-giant-tree时 出现 init of undefined，原因是我vue的index.html引用了jquery库冲突造成的，去掉index.html对jquery的引用就正常没问题。
但是因为一些原因index.html必须要引用jquery，请问有其他解决办法吗？

**Comment by tower1229** [comment]
这个问题最近刚解决过，我自己测试了外联引用jQuery的情况可以兼容，[兼容代码见这里](https://github.com/tower1229/Vue-Giant-Tree/blob/32565420f04f72fd7d2d042d53c575a92fcf2726/src/components/ztree.vue#L8)，方便的话你自己调试一下，我感觉不应该有问题
