### ISSUE TITLE
拖动功能无法正常使用

### ISSUE THREAD

**Issue by huihui91** [tower1229/Vue-Giant-Tree#4]
安装zTree设置拖动配置，拖动样式无法正常显示

**Comment by LiuZHolmes** [comment]
想请问这个问题会有计划修复吗

**Comment by tower1229** [comment]
> 想请问这个问题会有计划修复吗

应该是样式问题，会抽空修复

**Comment by LiuZHolmes** [comment]
![image](https://user-images.githubusercontent.com/16951022/93286033-cbbfe880-f808-11ea-9b8f-716690bc8e38.png)
原因应该是拖拽出来的元素在dom中并不处在zTree里，导致vue中scoped的css样式未能应用上。把这两个class的css样式都挪到外层就可以了。
![image](https://user-images.githubusercontent.com/16951022/93287246-98328d80-f80b-11ea-951c-c3939b48851c.png)

**Comment by tower1229** [comment]
> ![image](https://user-images.githubusercontent.com/16951022/93286033-cbbfe880-f808-11ea-9b8f-716690bc8e38.png)
> 原因应该是拖拽出来的元素在dom中并不处在zTree里，导致vue中scoped的css样式未能应用上。把这两个class的css样式都挪到外层就可以了。
> ![image](https://user-images.githubusercontent.com/16951022/93287246-98328d80-f80b-11ea-951c-c3939b48851c.png)

好的，修复了
