### ISSUE TITLE
import tree from 'vue-giant-tree' 时会出现 不识别init

### ISSUE THREAD

**Issue by xianggithubli** [tower1229/Vue-Giant-Tree#6]
`import tree from 'vue-giant-tree' `
时会出现 不识别init,但用
`tree: resolve => require(['./ztree.vue'], resolve)`
时，又没问题

**Comment by xianggithubli** [comment]
原来是项目中有其他地方使用了JQuery,可能与插件本身有冲突

**Comment by tower1229** [comment]
嗯，ztree需要默认引用jQuery，vue-giant-tree引用的是jQuery3.x，为了防止冲突判断了window上是否已经挂载jQuery对象：
```
import * as $ from "jquery";
if(!window.jQuery){
  window.jQuery = $;
}
```

**Comment by dialogueY** [comment]
修改webpack之后记得重启
