### ISSUE TITLE
hideNode showNode 等没有封装进去吗？

### ISSUE THREAD

**Issue by Liuxiao001** [tower1229/Vue-Giant-Tree#8]

**Comment by Liuxiao001** [comment]
我需要做一个模糊过滤关键词的功能

**Comment by Liuxiao001** [comment]
getNodesByParamFuzzy
找到了这个方法

**Comment by tower1229** [comment]
`onCreated`回调里可以得到ztree实例，你这些方法都可以通过实例调用

**Comment by Liuxiao001** [comment]
> `onCreated`回调里可以得到ztree实例，你这些方法都可以通过实例调用

exhide 扩展 的方法没有
onCreated 得到实例上没有这些方法
具体为hideNodes，hideNode，showNode，showNodes，isHidden

**Comment by tower1229** [comment]
哦，因为官网有这么一句话
`all.js = core + excheck + exedit ( 不包括 exhide )`
如果要用这个功能，可能你得自己构建一个版本了

**Comment by colo1994** [comment]
> 哦，因为官网有这么一句话
> `all.js = core + excheck + exedit ( 不包括 exhide )`
> 如果要用这个功能，可能你得自己构建一个版本了

打扰下，请问这个应该怎么构建？

**Comment by tower1229** [comment]
> > 哦，因为官网有这么一句话
> > `all.js = core + excheck + exedit ( 不包括 exhide )`
> > 如果要用这个功能，可能你得自己构建一个版本了
> 
> 打扰下，请问这个应该怎么构建？

https://github.com/tower1229/Vue-Giant-Tree/blob/master/src/components/ztree.vue#L11
