### ISSUE TITLE
vue2.6.11版本渲染giant-tree会出现所有所有节点都在一级目录

### ISSUE THREAD

**Issue by PepperKUN** [tower1229/Vue-Giant-Tree#9]
我用的是vue版本2.6.11, 放入示例数据后出现所有层级都在一级目录上
![sp200403_161346](https://user-images.githubusercontent.com/16114803/78338887-27cde200-75c6-11ea-82f0-b085492fe303.png)
项目本身没有报任何错误, 开发者工具查看dom结构发现所有的节点类目都为level0
![sp200403_161618](https://user-images.githubusercontent.com/16114803/78339079-7ed3b700-75c6-11ea-8420-40bc6f9dc7d2.png)
下面是项目的写法
![sp200403_161820](https://user-images.githubusercontent.com/16114803/78339263-c6f2d980-75c6-11ea-8635-611655b043fa.png)
请问下应该怎么解决?

**Comment by tower1229** [comment]
https://github.com/tower1229/Vue-Giant-Tree/blob/master/src/App.vue#L85
